---
title: "GEO DataSets: Experiment Selection and Initial Processing"
description: |
    A short description of the post.
author:
  - name: Feifei Li
    url: {}
date: 2021-06-07
output:
  distill::distill_article:
    self_contained: FALSE
    toc: TRUE
creative_commons: CC BY
categories:
    - R
    - bioconductor
    - bioinformatics
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


```{r, warning=FALSE}
query <- paste(
    "SELECT DISTINCT",
    "gse.title,",
    "gse.gse,",
    "gpl.title AS platform,",
    "gse.submission_date,",
    "gse.supplementary_file",
    "FROM",
    "gse JOIN gse_gpl ON gse_gpl.gse=gse.gse",
    "JOIN gpl ON gse_gpl.gpl=gpl.gpl",
    "WHERE",
    "gse.submission_date > '2015-01-01' AND",          # not older than 6 years
    "gse.title LIKE '%SARS-CoV-2%' AND ",               # something about covid
    "gpl.organism LIKE '%Homo sapiens%' AND", # a dataset human cells or tissue
    "gpl.technology LIKE '%high-throughput seq%' ",              # RNA-seq data
    sep = " ")
```